services:
  # Defines a service named "miniconda"
  miniconda: 
    # Assigns a specific name to the container
    container_name: remote_sensing_container 
    # Specifies the platform architecture for the container
    platform: linux/amd64
    # Configures how the container image is built
    build: 
      # Sets the build context to the current directory
      context: . 
      # Specifies the Dockerfile to use (defaults to Dockerfile if not specified)
      dockerfile: Dockerfile
      # Passes build arguments to the Dockerfile
      args:
      # Sets the PYTHON_VERSION build argument to 3.10
        PYTHON_VERSION: 3.10 
    volumes: # Defines volume mounts
      # Mounts the local "./projects" directory to "/workspace/projects" in the container
      - ./projects:/workspace/projects 
    environment: # Sets environment variables within the container
      # Sets the PYTHONPATH environment variable to "/workspace"
      - PYTHONPATH=/workspace 
    # Allocates a pseudo-TTY (enables interactive terminal)
    tty: true 
    # Keeps stdin open even if not attached (enables interactive terminal)
    stdin_open: true 
    # Overrides the default command to start a Bash shell
    command: /bin/bash 